Feat/add tracing id to log and errors
virtualidentityag/spring-boot-boilerplate pull request #49
Opened 2021-04-07 11:10 UTC by marcofenske-vi

Add Spring Sleuth to have tracing Ids in log messages and support dirtibuted tracing.
Also use traceIds as ids for error response objects.

2021-04-07 13:17 UTC, RafaelMarquesVI commented on src/main/java/com/myCompanyName/myProjectName/common/rest/error/RestExceptionHandler.java
> +  private RestErrorLogger restErrorLogger;
these could be final

2021-04-07 13:17 UTC, RafaelMarquesVI commented on src/main/java/com/myCompanyName/myProjectName/common/rest/error/RestExceptionHandler.java
> +  public RestExceptionHandler(final RestErrorBuilder restErrorBuilder, final RestErrorLogger restErrorLogger) {
aren't these autowired?

2021-04-07 13:17 UTC, RafaelMarquesVI commented on src/main/java/com/myCompanyName/myProjectName/common/rest/error/RestErrorBuilder.java
> +    private Tracer tracer;
could this be final?

2021-04-07 13:18 UTC, RafaelMarquesVI commented on src/main/java/com/myCompanyName/myProjectName/common/rest/error/RestErrorBuilder.java
> +    public RestErrorBuilder(final Tracer tracer) {
should this be autowired?

2021-04-07 18:55 UTC, frittinger commented
I like this addition!
I saw that there are plugins for queues which could be very interesting for IFX for the purging. However, I was wondering if there are also mechanisms to trace from the frontend (Javascript) through the backend. So to have a trace id in the log for a distinct AJAX call or similar from the frontend? I found nothing in the docs.

2021-04-08 05:38 UTC, marcofenske-vi commented on src/main/java/com/myCompanyName/myProjectName/common/rest/error/RestExceptionHandler.java
> +  public RestExceptionHandler(final RestErrorBuilder restErrorBuilder, final RestErrorLogger restErrorLogger) {
this IS autowiring (by constructor) 
Field injection is a bad practice, see https://reflectoring.io/constructor-injection/

2021-04-08 05:38 UTC, marcofenske-vi commented on src/main/java/com/myCompanyName/myProjectName/common/rest/error/RestErrorBuilder.java
> +    public RestErrorBuilder(final Tracer tracer) {
constructor injection (se above)

2021-04-12 04:32 UTC, ImpLarsBruemmer requested changes

2021-04-12 04:32 UTC, ImpLarsBruemmer commented on README.md
> +Further, trace ids are also forwarded automatically to other services called by Spring's RestTemplate that are also based on this boilerplate or include Spring Sleuth. This means that distributed tra
Hi @marcofenske-vi,

could you please provide an example log message to see which fields are actually available and how the format does look like?

2021-04-12 13:24 UTC, marcofenske-vi commented on README.md
> +Further, trace ids are also forwarded automatically to other services called by Spring's RestTemplate that are also based on this boilerplate or include Spring Sleuth. This means that distributed tra
Done

2021-04-13 05:26 UTC, ImpLarsBruemmer approved these changes

2021-04-13 08:29 UTC, merged